version: "3.1"

services:
    www:
        build: .
        ports: 
            - "8000:80"
        volumes:
            - ./src/:/var/www/html/
        links:
            - db
        networks:
            - default

    db:
        image: mysql:8.0
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_USER: admin
            MYSQL_PASSWORD: docker@01
            MYSQL_ROOT_PASSWORD: dockroot@01
        volumes:
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8001:80
        environment:
            MYSQL_USER: admin
            MYSQL_PASSWORD: docker@01
            MYSQL_ROOT_PASSWORD: dockroot@01

volumes:
    persistent:
